services:
  app:
    build: .
    image: vas-app:dev
    container_name: vas-app
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    command: pnpm start
  postgres:
    image: postgres:16-alpine
    container_name: vas-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: vas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: vas-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
volumes:
  pgdata:
